---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios'
    msg: "Network device OS not defined or not supported by this role: {{ ansible_network_os }}"

- name: Add/remove nxos static routes
  nxos_static_route:    
      prefix: "{{ item.prefix | default(omit) }}"
      tag: "{{ item.route_tag | default('up') }}"
      state: "{{ item.state | default('present') }}"
      next_hop: "{{ item.next_hop | default(omit) }}"
      route_name:  "{{ item.nh_name | default(omit) }}"
      pref: "{{ item.admin_distance | default(omit) }}"
      vrf: "{{ item.vrf | default(omit) }}"
  with_items: "{{ static_routes }}"    
  when: >
    ansible_network_os == 'nxos'  
  tags: 
    - static_routes_config
    - nxos


